### ISSUE TITLE
[REQ] ULID support

### ISSUE THREAD

**Issue by koddek** [dtanglr/Primitively#11]
This library is awesome! I started working on my own but it was a single object for each primitive that I use, like Username, Name, Id etc. Then I found this... I am ashamed of myself :)

Can you add support for Ulid (sortable ids) like you did with Guid?
Here is the C# package link: [ULID](https://github.com/Cysharp/Ulid)

**Comment by dtanglr** [comment]
Thank you so much and apologies for not replying sooner. Sortable GUIDs are on my list. I will take a look at ULID. I see Microsoft has added support in .net 9 too.

**Comment by koddek** [comment]
Yes the new v7 uuid in .net 9 would be better.

**Comment by dtanglr** [comment]
@koddek I've included the .net 9 v7 uuid implementation in the latest 1.4.22 release (see the release/1.4.22 branch in GitHub)
